name: Create Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version from fxmanifest.lua
        id: get_version
        run: |
          version=$(grep "version" fxmanifest.lua | grep -o "'.*'" | tr -d "'")
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create ZIP archive
        run: |
          zip -r sure_lib.zip . -x ".git/*" ".github/*" "*.md" "LICENSE"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "sure_lib.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          generateReleaseNotes: true
          tag: v${{ steps.get_version.outputs.version }}
          name: "Release v${{ steps.get_version.outputs.version }}"
