name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create ZIP archive
        run: |
          zip -r sure_lib.zip . -x ".git/*" ".github/*" "*.md" "LICENSE"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "sure_lib.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          generateReleaseNotes: true
